name: docs_pages_workflow
# execute this workflow automatically when we push to master

on:
  push:
    branches: [master]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_ACTOR: github-actions[bot]

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme

      - name: Set Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Merge master to gh-pages
        run: |
          git fetch --unshallow
          git checkout gh-pages
          git pull
          git merge -X theirs --no-ff origin/master -m "Auto-merge master to gh-pages"
      - name: Build GitHub pages
        run: |
          cd docs
          sphinx-build -M html source build
          cp -a ./build/html/. .
          rm -rf ./build/
          git add ..
          git commit -m "Documentation for version"
          git push origin gh-pages
